services:
  - type: web
    name: number-brawl-online
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /healthz
    maxShutdownDelaySeconds: 10
